import { Paintings } from "../../types/paintingTypes";

export const mockToken = "mockToken";

export const mockPaintings: Paintings = [
  {
    id: "1",
    author: "Mary Heilmann",
    name: "New Line Up",
    year: "2018",
    gallery: "Private collection",
    technique: "Oil on canvas",
    size: "40 x 50 in",
    medium: "Painting",
    materials: "Oil paint, canvas",
    unique: "true",
    certificate: "true",
    rarity: "unique",
    condition: "excellent",
    signature: "true",
    price: "28000",
    frame: "false",
    highlightOrder: "1",
    summary:
      "Colorful abstract painting with horizontal lines and curved shapes",
    image:
      "https://icqwpkxwddqofeibjqcj.supabase.co/storage/v1/object/public/paitings/newLineUp.png?t=2023-03-12T13%3A23%3A46.999Z",
    width: "300",
    height: "400",
  },
  {
    id: "2",
    author: "Charles Ray",
    name: "Untitled",
    year: "1991",
    gallery: "Museum of Modern Art, New York",
    technique: "Mixed media",
    size: "Dimensions variable",
    medium: "Oil on canvas",
    materials: "Oil paint, canvas",
    unique: "true",
    certificate: "false",
    rarity: "unique",
    condition: "excellet",
    signature: "false",
    price: "3000",
    frame: "false",
    highlightOrder: "1",
    summary: "Floral mural",
    image:
      "https://icqwpkxwddqofeibjqcj.supabase.co/storage/v1/object/public/paitings/charlesRayUntilted.png?t=2023-03-11T16%3A11%3A40.075Z",
    width: "300",
    height: "400",
  },
  {
    id: "615b507f92afda1a6a9c6d2f",
    author: "Gary Komarin",
    name: "Big Pink, Luxor",
    year: "2018",
    technique: "Oil on Canvas",
    size: "120 x 120 cm",
    medium: "Oil Paint",
    materials: "Canvas, Wood",
    unique: "true",
    certificate: "false",
    rarity: "unique",
    condition: "excellent",
    signature: "false",
    price: "2500",
    frame: "true",
    summary:
      "Bright and bold abstract painting by Gary Komarin, featuring a vibrant pink color palette and expressive brushstrokes.",
    image:
      "https://icqwpkxwddqofeibjqcj.supabase.co/storage/v1/object/public/paitings/uploads/bigPink.png?t=2023-03-20T12%3A41%3A30.457Z",
    highlightOrder: "0",
    gallery: "Private Collection",
    height: "468",
    width: "443",
  },
  {
    id: "6415d0a9e31a17c33ee21ebb",
    author: "Tiger Rocha",
    name: "Charge",
    year: "2023",
    gallery: "Curator's choice",
    technique: "Oil on canvas",
    size: "36 × 30 in | 91.4 × 76.2 cm",
    medium: "Painting",
    materials: "Oil on canvas",
    unique: "true",
    certificate: "true",
    rarity: "unique",
    condition: "excellent",
    signature: "true",
    price: "5000",
    frame: "false",
    summary: "",
    image:
      "https://icqwpkxwddqofeibjqcj.supabase.co/storage/v1/object/public/paitings/uploads/ticherRocha.png?t=2023-03-20T12%3A42%3A16.395Z",
    width: "1174",
    height: "1379",
  },
];
